name: Python Package using Conda
on:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  test:
    name: Test python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: intall mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
          miniforge-version: latest
          environment-file: DR.yml
          environment-name: DR
      - name: Install test packages
        shell: bash -l {0}
        run: |
          pip install pytest nbconvert nbformat
      - name: which python
        shell: bash -l {0}
        run: |
          which python
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest .github/workflows/test_DR_notebooks.py
